---
title: "TidyTuesday — Week 30"
subtitle: "2026-07-26"
author:
  - name: Thomas Reinke
    affiliation:
      - name: Baylor University
        department: Statistics Department
        city: Waco
        state: TX
        country: US
        url: https://www.baylor.edu
    email: thomas_reinke1@baylor.edu
date-format: "MMMM d, yyyy"
format:
  html:
    code-tools:
      source: false
    page-layout: full
    toc-expand: 2
    anchor-sections: false
    citations-hover: true
    footnotes-hover: true
    crossrefs-hover: true
    toc-location: right
    other-links:
      - text: GitHub
        href: https://github.com/thomasqmd
        icon: github
      - text: Website
        href: https://thomasqmd.quarto.pub/website/
        icon: globe
      - text: LinkedIn
        href: https://www.linkedin.com/in/thomas-reinke1
        icon: linkedin
theme: [materia, ../../quarto-assets/baylor-html-theme.scss]
code-fold: true
code-overflow: wrap
highlight-style: a11y
toc: true
toc-depth: 5
number-sections: false
number-depth: 1
callout-appearance: minimal
lightbox:
  loop: true
embed-resources: true
editor:
  markdown:
    wrap: 72
---

```{r, setup}
#| include: false
#| message: false
#| eval: true
library(knitr)
library(tidyverse)
library(conflicted)
library(janitor)
library(kableExtra)
library(plotly)
library(patchwork)
conflicted::conflict_prefer("filter", "dplyr")
conflicted::conflict_prefer("select", "dplyr")
conflicted::conflicts_prefer(plotly::layout)
knitr::opts_chunk$set(
  comment = "#>",
  message = FALSE,
  warning = FALSE,
  cache = FALSE,
  echo = TRUE,
  eval = TRUE,
  tidy.opts = list(width.cutoff = 100),
  tidy = FALSE,
  fig.align = "center"
)
ggplot2::theme_set(ggplot2::theme_minimal())
ggplot2::theme_update(panel.grid.minor = ggplot2::element_blank())
```

# Week Name

## Data

Load the week's data from the `data/` folder:

```{r load-data}
data <- read_csv("data/nde_experiences.csv")
glimpse(data)
```

## Analysis

Start your analysis here.

